#!/bin/bash

set -eo pipefail

VERBOSE=0

CMDLINE=$(getopt -o 'v' --long 'verbose' -- "$@")
eval set -- "$CMDLINE"

while true; do
  TOKEN="$1"; shift
  case "$TOKEN" in
    -v|--verbose)
      VERBOSE=1
      ;;
    --)
      break
      ;;
  esac
done

SCRIPTS=()

SCRIPTS+=("spo/mas/example/basic/log.INFO.mas")

if [[ $VERBOSE -ne 0 ]]; then
  SCRIPTS+=("spo/mas/example/basic/summarize.mas")
fi
SCRIPTS+=("spo/mas/example/basic/compute.wsize.mas")
SCRIPTS+=("spo/mas/example/roofline/compute.Q.mas")
SCRIPTS+=("spo/mas/example/roofline/compute.W.TFL.mas")

spo/mas/dev analyze-tflite --model "$1" "${SCRIPTS[@]}" <(
  echo "mas = get_mas_session()"
  echo
  echo "W = mas.get_attr('roofline.W.model')"
  echo "Q_IDEAL = mas.get_attr('roofline.Q.model.ideal')"
  echo "Q_LBL = mas.get_attr('roofline.Q.model.layer_by_layer')"
  echo "WGT_SIZE = mas.get_attr('basic.wsize')"
  echo
  echo "print(f'W                 : {W} OPS')"
  echo "print(f'Q          (ideal): {Q_IDEAL} bytes')"
  echo "print(f'Q (layer-by-layer): {Q_LBL} bytes')"
  echo "print(f'WGT_SIZE          : {WGT_SIZE} bytes')"
)
