version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - run:
          name: Update
          command: apt update -y

      - run:
          name: Install
          command: |
            apt install -y git ssh
            apt install -y cmake gcc g++
            apt install -y libprotobuf-dev protobuf-compiler

      - checkout

      - run:
          name: Configure and Build
          command: |
            ./alex configure
            ./alex build
            ./alex test

  infra_applet_test:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt update -y
            # For 'python3' domain
            apt install -y python3 python3-venv
      - checkout
      - run:
          name: Run framework tests
          working_directory: infra/applet
          command: |
            ./test-manage tests/UC000
      - run:
          name: Run bash domain tests
          working_directory: infra/applet
          command: |
            ./test-domain bash domain/bash/samples/r1.0
      - run:
          name: Run python3 domain tests
          working_directory: infra/applet
          command: |
            ./test-domain python3 domain/python3/samples/r1.0
      - run:
          name: Rhe python3 domain tutorial
          command: |
            ./alex applet install infra/applet/domain/python3/samples/r1.0
            ./alex applet run r1.0
            ./alex applet uninstall r1.0

workflows:
  commit_check:
    jobs:
      - build
      - infra_applet_test
