#!/bin/bash

# HOW TO USE
#
# $ ./alex app-invoke [APP NAME] ...
#
APP_NAME="$1"; shift

# Each Alex Application may use the following variables
APP_CODE_DIR="${ALEX_PROJECT_PATH}/code/${APP_NAME}"
# TODO Set "APP_DATA_DIR"
# - APP_DATA_DIR points to a storage dedicated to each application

# TODO Check whether "app.manifest" exists or not
source "${APP_CODE_DIR}/app.manifest"

# TODO Show an error message when "invoke" function is not defined
invoke "$@"
