
all: clean build install

clean:
	make -f Makefile.ptrace clean
#	make -f Makefile.so clean
#	make -f Makefile.wrapper clean

build:
	make -f Makefile.ptrace build
#	make -f Makefile.so build
#	make -f Makefile.wrapper build

install:
	make -f Makefile.ptrace install
#	make -f Makefile.so install
#	make -f Makefile.wrapper install	
